### ISSUE TITLE
Entity death error

### ISSUE THREAD

**Issue by funnybunnyofdoom** [funnybunnyofdoom/Vintage-Story-Mods#223]
25.5.2023 05:46:21 [Server Fatal] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at blocklog.src.BlockLog.onEntityDeath(Entity entity, DamageSource damageSource)
   at Vintagestory.API.Common.Entities.Entity.Die(EnumDespawnReason reason, DamageSource damageSourceForDeath) in C:\Games\Vintagestory\devnet6\VintagestoryApi\Common\Entity\Entity.cs:line 1631
   at Vintagestory.GameContent.EntityBlockFalling.OnGameTick(Single dt) in C:\Games\Vintagestory\devnet6\VSEssentials\Entity\EntityBlockFalling.cs:line 316
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 301
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 163
   at Vintagestory.Server.ServerMain.Process() in C:\Games\Vintagestory\devnet6\VintagestoryLib\Server\ServerMain.cs:line 818

**Comment by funnybunnyofdoom** [comment]
This was a death in server-owned (or trader owned) property that couldn't recall the owner name
